language: php
php:
  - 7.0
  - 7.1 
  #- nightly

before_install:
  - composer self-update

install:
  - composer install --prefer-dist --optimize-autoloader --quiet

before_script:
  - cp .env.example .env
  - php artisan key:generate

script:
  - mkdir -p build/logs
  - phpunit -c phpunit.xml --coverage-clover build/logs/clover.xml

addons:
  code_climate:
    repo_token: 5bb3f20c25e5672e4fa1f4d4a14cc4c1a0f6211b6e1db87967af12eafc17a138

after_success:
  - vendor/bin/test-reporter
  
