language: php
php:
  #- 5.6
  #- 7.0
  - 7.1
  - 7.2
  #- nightly

#sudo: required
#dist: trusty

cache:
  directories:
      - node_modules
      - vendor
      - $HOME/.composer/cache

services:
  - mysql
  #- elasticsearch

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS homestead;'
  - nvm install 6.9.4
  - nvm use 6.9.4

install:
  - composer install --prefer-dist --optimize-autoloader --quiet
  - npm install

before_script:
  - cp .env.example .env
  - php artisan key:generate
  # for dusk testing
  #- export DISPLAY=:99.0
  #- sh -e /etc/init.d/xvfb start
  #- ./vendor/laravel/dusk/bin/chromedriver-linux &
  #- php artisan serve &

script:
  - npm run prod
  - ./vendor/bin/phpunit -c phpunit.xml --exclude-group none --coverage-clover build/logs/clover.xml
  #- php artisan dusk

after_success:
  - travis_retry php vendor/bin/coveralls

notifications:
  email: false
  slack:
    secure: TO1xm9gSf3pNq8GPVg1ci6aviXdnS7v1mZ8xo6QMJ6XP9auq/9Y1UspHmrVVK9TZQGjk1SkomxehJ1XhfQpzehnN8qXGqLACrynhEyY5NNN8GZdJIikke/WgFquvrHmHLmVBpoFcbTpqy54+ET7ZfZ5iWEsnAjgDsivOYacIr7ZrRZ/MzW/zADrYEwfVAMdbmt14va0UZSsvV/YhN5eBYgCNTMOweVFWRnPz9QAja++jwgGgqivOM9qYl1nGxl9/QVUZJDzjoC0LSHMnSXswP4Oye8izEDreHRhgnaEz5kdbrxQ5t/Jy6yGgls911R9ppTnvyIUOuMopwBxTrA7Ya1pGuftz+PdAWf/N51NYI6rOZ73Z099dobFhg6lavkLc6zdsna+fnhKbRw77uHvLkB7gWtdSLbm0wI0U0H/7qPZA2BAGuc8U678pH+mEptcuh7FBdYkrI0BKMZC0Oq4qByy8BzSTpfkPvAna1BPOun2qNjE4EDqaokncone8sNtJNuGUkwohpQ3hUIGFVUea0M5MUpH6zASvHG0UwPALlesOYK0b90ke16uJOqv7W2nX8o2Sfg7fkGmRMJPW+4s41wdRv7HqNhW6H7Q3N8OrAg9YGCNSQcGmSpqt2FuRTLNSBbsMVBUYa7BqVZRrrCF17SodXhoL+mN6w+vzJEAdsdQ=
