language: php
php:
  - 7.0
  - 7.1 
  #- nightly

before_install:
  - composer self-update

install:
  - composer install --prefer-dist --optimize-autoloader --quiet

before_script:
  - cp .env.example .env
  - php artisan key:generate

script: phpunit -c phpunit.xml --coverage-text --coverage-clover=coverage.xml
