language: php
php:
  - 7.1

install:
  - composer install --prefer-dist --optimize-autoloader --quiet

before_script:
  - cp .env.example .env
  - php artisan key:generate

script: phpunit -c phpunit.xml --coverage-text
