language: php
php:
  - 7.0
  - 7.1
  #- nightly

before_install:
  - composer self-update

install:
  - composer install --prefer-dist --optimize-autoloader --quiet

before_script:
  - cp .env.example .env
  - php artisan key:generate
  - echo $'\nSTRIPE_SECRET=sk_test_O0v1qLvKpeF5MWfm7f8Nuaku\n' >> .env

script:
  - phpunit -c phpunit.xml --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/coveralls

notifications:
  slack:
    secure: TO1xm9gSf3pNq8GPVg1ci6aviXdnS7v1mZ8xo6QMJ6XP9auq/9Y1UspHmrVVK9TZQGjk1SkomxehJ1XhfQpzehnN8qXGqLACrynhEyY5NNN8GZdJIikke/WgFquvrHmHLmVBpoFcbTpqy54+ET7ZfZ5iWEsnAjgDsivOYacIr7ZrRZ/MzW/zADrYEwfVAMdbmt14va0UZSsvV/YhN5eBYgCNTMOweVFWRnPz9QAja++jwgGgqivOM9qYl1nGxl9/QVUZJDzjoC0LSHMnSXswP4Oye8izEDreHRhgnaEz5kdbrxQ5t/Jy6yGgls911R9ppTnvyIUOuMopwBxTrA7Ya1pGuftz+PdAWf/N51NYI6rOZ73Z099dobFhg6lavkLc6zdsna+fnhKbRw77uHvLkB7gWtdSLbm0wI0U0H/7qPZA2BAGuc8U678pH+mEptcuh7FBdYkrI0BKMZC0Oq4qByy8BzSTpfkPvAna1BPOun2qNjE4EDqaokncone8sNtJNuGUkwohpQ3hUIGFVUea0M5MUpH6zASvHG0UwPALlesOYK0b90ke16uJOqv7W2nX8o2Sfg7fkGmRMJPW+4s41wdRv7HqNhW6H7Q3N8OrAg9YGCNSQcGmSpqt2FuRTLNSBbsMVBUYa7BqVZRrrCF17SodXhoL+mN6w+vzJEAdsdQ=
