language: php
php:
  - 7.1

before_script:
  - composer install --dev --no-interaction --prefer-source
  - cp ./.env.example ./.env
  - php artisan key:generate

script: phpunit --configuration phpunit.xml
