name: CI
on: [push]
jobs:
  phpunit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Copy env
        run: cp .env.example .env
      - name: Install dependencies
        run: |
          composer install --prefer-dist --optimize-autoloader
          npm install
      - name: Generate key
        run: php artisan key:generate
      - name: Package npm for production
        run: npm run prod
      - name: Run tests
        run: vendor/bin/phpunit
  dusk-php-latest:
    runs-on: ubuntu-latest
    container: docker://zaherg/laravel-dusk:latest
    steps:
      - uses: actions/checkout@master
      - name: Copy env
        run: cp .env.example .env
      - name: Install Composer dependencies
        run: |
          composer install --prefer-dist --optimize-autoloader
          npm install
      - name: Generate key
        run: php artisan key:generate
      - name: Package npm for production
        run: npm run prod
      - name: Run dusk tests
        run: |
          php artisan dusk:chrome-driver
          nohup bash -c './vendor/laravel/dusk/bin/chromedriver-linux > /dev/null 2>&1 &'
          nohup bash -c 'php artisan serve > /dev/null 2>&1 &'
          php artisan dusk
