name: CI
on: [push]
jobs:
  phpunit:
    runs-on: ubuntu-latest
    steps:
      - name: show php version
        run: php -v
      - name: Checkout
        uses: actions/checkout@master
      - name: Copy env
        run: cp .env.example .env
      - name: Install dependencies
        run: |
          composer install --prefer-dist --optimize-autoloader
          npm install
      - name: Generate key
        run: php artisan key:generate
      - name: Package npm for production
        run: npm run prod
      - name: Run tests
        run: vendor/bin/phpunit
  dusk-php-latest:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: homestead
          MYSQL_ROOT_PASSWORD:
        ports:
          - '3306:3306'
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: show php version
        run: php -v
      - name: create database
        run: mysql -h 127.0.0.1 --port 3306 -u root -e 'CREATE DATABASE IF NOT EXISTS homestead'
      - name: Checkout
        uses: actions/checkout@master
      - name: Copy env
        run: cp .env.example .env
      - name: Install Composer dependencies
        run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader
      - name: Generate Application Key
        run: php artisan key:generate
      - name: Install npm dependencies
        run: npm install
      - name: Install laravel dusk
        run: php artisan dusk:install
      - name: Start Chrome Driver
        run: ./vendor/laravel/dusk/bin/chromedriver-linux > /dev/null 2>&1 &
      - name: Run Laravel Server
        run: php artisan serve > /dev/null 2>&1 &
      - name: Run Dusk Tests
        run: php artisan dusk
