name: create a draft release note (github-script)

on:
  workflow_dispatch:
    inputs:
      ProjectsColumnName:
        description: 'target column name in github projects (e.g. stage)'
        required: true
      Tag:
        description: 'the tag you want to use in this release (e.g. v1.0.0)'
        required: true


jobs:
  create-draft-release-note-in-github-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v4
        with:
#           github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const project = github.rest.projects.get({
              project_id: 2
            })
            console.log(project)
